name: build
on:
 - push
jobs:
  build-status:
    runs-on: ubuntu-latest
    steps:
      - name: setup node.js environment
        uses: actions/setup-node@v4.0.4
        with: 
         node-version: 20.x
      - name: check the node version
        run: node -v
      - name: check the npm version
        run: npm -v
      - name: list the root directory of container
        run: ls
      - name: installing all dependencies
        run: npm install
      - name: create build folder
        run: npm run build
      - run: echo "ğŸ This job's status is ${{ job.status }}."
        
      
